services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/er_bal
      SPRING_DATASOURCE_USERNAME: my_user
      SPRING_DATASOURCE_PASSWORD: my_password

  database:
    build: ./database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: er_bal
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

