-- 새 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

-- 새 사용자 생성 및 권한 부여
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';
FLUSH PRIVILEGES;

