name: Run Backend Tests on PR Branch

on:
  pull_request:
    branches:
      - main # PR이 main 브랜치에 대해 열릴 때

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # 현재 PR에서 작성한 브랜치 체크아웃

      # JDK 설치 (Java 프로젝트인 경우 예시)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # 의존성 설치 및 테스트 실행
      - name: Run Gradle tests
        run: |
          ./gradlew test # 또는 적절한 테스트 실행 명령어
          
      # 빌드 후 실패 시 PR 머지 방지
      - name: Prevent merge on failed tests
        if: failure()  # 테스트가 실패한 경우
        run: exit 1

