name: Run Backend Tests

on:
  push:
    branches:
      - deploy
    paths:
      - 'backend/**'

  pull_request:
    branches:
      - develop # PR이 main 브랜치에 대해 열릴 때
    types:
      - opened
      - synchronize
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 체크아웃
      - name: Checkout the PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # 현재 PR에서 작성한 브랜치 체크아웃

      # JDK 설치
      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'  # JDK 배포판을 지정
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}

      # changelog file 유무 확인
      - name: Verify changelog file
        run: ls -R src/main/resources/db/changelog

      # 의존성 설치 및 테스트 실행
      - name: Run Gradle tests
        run: |
          cd backend
          ./gradlew test # 또는 적절한 테스트 실행 명령어
          
      # 빌드 후 실패 시 PR 머지 방지
      - name: Prevent merge on failed tests
        if: failure()  # 테스트가 실패한 경우
        run: exit 1

