name: Run E2E Tests

on:
  pull_request:
    branches:
      - deploy
      - develop
    types:
      - opened
      - synchronize

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.6
        options: --privileged
        ports:
          - "8080:8080"
          - "3000:3000"

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 파이썬 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 3. Docker Compose 설치
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.32.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
          sudo chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          sudo ln -s $DOCKER_CONFIG/cli-plugins/docker-compose /usr/local/bin/docker-compose
          docker-compose version

      # 4. .env.test 생성
      - name: Create .env.test file
        run: |
          echo "MYSQL_DATABASE=${{ secrets.E2E_MYSQL_DATABASE }}" >> .env.test
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.E2E_MYSQL_ROOT_PASSWORD }}" >> .env.test
          echo "MYSQL_USER=${{ secrets.E2E_MYSQL_USER }}" >> .env.test
          echo "MYSQL_PASSWORD=${{ secrets.E2E_MYSQL_PASSWORD }}" >> .env.test
          echo "API_URL=${{ secrets.E2E_API_URL }}" >> .env.test

      # 5. Docker 서비스 시작
      - name: Start Docker
        run: |
          docker-compose -f docker-compose.e2e-test.yml --env-file .env.test up --build -d

      # 6. E2E 테스트를 위한 패키지 설치
      - name: Set up E2E Test Environment
        working-directory: ./e2e-tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # 7. 여러 브라우저로 pytest 실행
      - name: Run E2E Tests
        working-directory: ./e2e-tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: |
          source venv/bin/activate
          pytest --browser $BROWSER

    strategy:
      matrix:
        browser: [chrome, firefox, safari]

